#!/bin/bash

#$ -M jdasilv2@nd.edu   # Email address for job notification
#$ -m abe              # Send mail when job begins, ends and aborts
#$ -pe smp 12          # Specify parallel environment and legal core size
#$ -q long             # Specify queue
#$ -N model_analysis   # Specify job name
conda activate HFStudy
#cd ../../AnalyticaML
#pip install .
#cd ../model-evolution/scripts

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 3000 --end 4000
./notify.sh "DONE" "3000 -- 4000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 4000 --end 5000
./notify.sh "DONE" "4000 -- 5000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 5000 --end 6000
./notify.sh "DONE" "5000 -- 6000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 6000 --end 7000
./notify.sh "DONE" "6000 -- 7000"


