#!/bin/bash

#$ -M jdasilv2@nd.edu   # Email address for job notification
#$ -m abe              # Send mail when job begins, ends and aborts
#$ -pe smp 12          # Specify parallel environment and legal core size
#$ -q long             # Specify queue
#$ -N model_analysis   # Specify job name
conda activate HFStudy
cd ../../AnalyticaML
pip install .
cd ../model-evolution/scripts
HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 0 --end 3 # Application to execute
