#!/bin/bash

#$ -M jdasilv2@nd.edu   # Email address for job notification
#$ -m abe              # Send mail when job begins, ends and aborts
#$ -pe smp 12          # Specify parallel environment and legal core size
#$ -q long             # Specify queue
#$ -N model_analysis   # Specify job name
conda activate HFStudy
#cd ../../AnalyticaML
#pip install .
#cd ../model-evolution/scripts

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 7000 --end 8000
./notify.sh "DONE" "7000 -- 8000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 8000 --end 9000
./notify.sh "DONE" "8000 -- 9000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 9000 --end 10000
./notify.sh "DONE" "9000 -- 10000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 10000 --end 11000
./notify.sh "DONE" "10000 -- 11000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 11000 --end 12000
./notify.sh "DONE" "11000 -- 12000"

HF_HUB_CACHE=/groups/jdasilv2/hf_cache HF_HUB_ENABLE_HF_TRANSFER=1 python analyze_commit_history.py --group_type recent --begin 12000 --end 13000
./notify.sh "DONE" "12000 -- 13000"