#!/bin/bash

#$ -M jdasilv2@nd.edu   # Email address for job notification
#$ -m abe              # Send mail when job begins, ends and aborts
#$ -pe smp 12          # Specify parallel environment and legal core size
#$ -q long             # Specify queue
#$ -N model_analysis   # Specify job name
conda activate HFStudy
python get_commit_logs.py recent  # Application to execute
python analyze_commit_history.py recent  # Application to execute
